name: getx_demo1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  lottie: ^3.3.1
  get_storage: ^2.1.1
  flutter_smart_dialog: ^4.9.7+9
  # 内购
  in_app_purchase: ^3.2.0
  in_app_purchase_storekit: ^0.4.4
  in_app_purchase_android: ^0.4.0+5
  flutter_secure_storage: ^9.2.2
  # 数据库
  drift: ^2.19.1+1
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  drift_db_viewer: ^2.1.0
  # 工具
  logger: ^2.4.0
  connectivity_plus: ^7.0.0
  # 网络请求
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  retry: ^3.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
